# Generated by Django 3.0.2 on 2020-09-12 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction', models.CharField(max_length=200, verbose_name='Tipo de Estrutura')),
                ('owner', models.CharField(max_length=80, verbose_name='Proprietário')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('total_time', models.CharField(max_length=30, verbose_name='Tempo total')),
                ('total_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor total')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=4, verbose_name='Identificador')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('task_text', models.TextField(verbose_name='Descrição da Tarefa')),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(verbose_name='Termino')),
                ('progress', models.CharField(max_length=3, verbose_name='Progresso %')),
                ('dependencies', models.CharField(max_length=10, verbose_name='Dependências')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('chronogram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='confidencechronograms.Chronogram')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_nascimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, max_length=9, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=30, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=30, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado Civil')),
                ('endereco', models.CharField(max_length=60, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('senha', models.CharField(blank=True, max_length=16, null=True)),
                ('fone1', models.CharField(max_length=16, verbose_name='Telefone 1')),
                ('fone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('dt_admissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('cargo', models.CharField(blank=True, max_length=20, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('bloqueado', models.CharField(max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('usuario_fun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('razao_social', models.CharField(max_length=60, verbose_name='Razão Social')),
                ('tipo_pessoa', models.CharField(max_length=8, verbose_name='Tipo de Pessoa')),
                ('cpf_cnpj', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('rg_ie', models.CharField(max_length=20, verbose_name='RG/IE')),
                ('dt_nascimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, max_length=9, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=30, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=30, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado Civil')),
                ('endereco', models.CharField(max_length=60, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('uf', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=60)),
                ('email2', models.EmailField(blank=True, max_length=60, null=True)),
                ('fone1', models.CharField(max_length=16, verbose_name='Telefone 1')),
                ('fone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('valor_permitido', models.FloatField(blank=True, null=True, verbose_name='Valor Permitido')),
                ('dias_vencimento', models.CharField(blank=True, max_length=8, null=True, verbose_name='Dias de Vencimento')),
                ('fax', models.CharField(blank=True, max_length=16, null=True)),
                ('bloqueado', models.CharField(blank=True, max_length=3, null=True)),
                ('banco', models.IntegerField(blank=True, null=True)),
                ('agencia', models.CharField(blank=True, max_length=10, null=True)),
                ('conta', models.CharField(blank=True, max_length=16, null=True)),
                ('valor_debito', models.FloatField(blank=True, null=True, verbose_name='Valor de Débito')),
                ('dia_debito', models.DateTimeField(blank=True, null=True, verbose_name='Dia do Débito')),
                ('dia_venc', models.DateTimeField(blank=True, null=True, verbose_name='Dia do Vencimento')),
                ('senha', models.CharField(blank=True, max_length=6, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='confidencechronograms.Funcionario')),
                ('usuario_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='chronogram',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='confidencechronograms.Cliente'),
        ),
        migrations.AddField(
            model_name='chronogram',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
