# Generated by Django 3.0.2 on 2020-01-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chronogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=80)),
                ('owner', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('total_time', models.CharField(max_length=30)),
                ('total_price', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
