# Generated by Django 3.0.2 on 2020-01-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('chronogram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='confidence_chronograms.Chronogram')),
            ],
            options={
                'verbose_name': 'Tasks',
            },
        ),
    ]
