# Generated by Django 3.0.2 on 2020-02-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
    ]
