# Generated by Django 3.0.2 on 2020-02-08 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confidence_chronograms', '0003_auto_20200207_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chronogram',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='chronogram',
            name='client',
            field=models.CharField(max_length=80, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='chronogram',
            name='construction',
            field=models.CharField(max_length=200, verbose_name='Tipo de Estrutura'),
        ),
        migrations.AlterField(
            model_name='chronogram',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='chronogram',
            name='total_price',
            field=models.CharField(max_length=20, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='chronogram',
            name='total_time',
            field=models.CharField(max_length=30, verbose_name='Tempo total'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.CharField(max_length=30, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.CharField(max_length=10, verbose_name='Termino'),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.CharField(max_length=10, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(verbose_name='Dscrição da Tarefa'),
        ),
    ]
