# Generated by Django 3.0.2 on 2020-02-08 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0005_auto_20200208_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chronogram',
            old_name='user',
            new_name='usuario',
        ),
    ]
