# Generated by Django 3.0.2 on 2020-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0006_auto_20200208_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(verbose_name='Termino'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(verbose_name='Inicio'),
        ),
    ]
