# Generated by Django 3.0.2 on 2020-02-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0007_auto_20200213_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor'),
        ),
    ]
