# Generated by Django 3.0.2 on 2020-02-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0008_auto_20200213_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronogram',
            name='total_price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor total'),
        ),
    ]
