# Generated by Django 3.0.2 on 2020-03-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0011_auto_20200308_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=1, max_length=40, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chronogram',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='confidence_chronograms.Cliente'),
            preserve_default=False,
        ),
    ]
