# Generated by Django 3.0.2 on 2020-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0012_auto_20200309_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(default=1, max_length=3, verbose_name='Progresso %'),
            preserve_default=False,
        ),
    ]
