# Generated by Django 3.0.2 on 2020-03-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0013_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.CharField(default=1, max_length=10, verbose_name='Dependências'),
            preserve_default=False,
        ),
    ]
