# Generated by Django 3.0.2 on 2020-03-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_chronograms', '0014_task_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ident',
            field=models.CharField(default=1, max_length=4, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
